# Generated by Django 4.1.2 on 2022-10-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image1',
            field=models.ImageField(upload_to='images/images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image2',
            field=models.ImageField(upload_to='images/images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image3',
            field=models.ImageField(upload_to='images/images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image4',
            field=models.ImageField(upload_to='images/images'),
        ),
    ]
