# Generated by Django 4.1.2 on 2022-10-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='sale',
            field=models.IntegerField(blank=True, default=100, max_length=50),
            preserve_default=False,
        ),
    ]
