# Generated by Django 4.1.2 on 2022-10-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_orders_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='address3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='address4',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
