# Generated by Django 4.1.2 on 2022-11-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_categoryoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('building', models.CharField(blank=True, max_length=250)),
                ('street', models.CharField(blank=True, max_length=250)),
                ('area', models.CharField(blank=True, max_length=250)),
                ('po', models.CharField(blank=True, max_length=250)),
                ('district', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
