# Generated by Django 4.1.2 on 2022-11-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Address',
        ),
    ]
